### ISSUE TITLE
Activar Projects

### ISSUE THREAD

**Issue by Jonathans0ramirez** [Presi-organization/Botrucho#4]
@presi11 Solo actíveme los proyectos para tener tareas melas 😂

**Comment by presi11** [comment]
https://github.com/orgs/Presi-organization/projects/1/views/1 te deja ingresar

**Comment by Jonathans0ramirez** [comment]
Ni idea cómo funka entonces 🧛🏼

**Comment by Jonathans0ramirez** [comment]
Funkó
